apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api-deployment
  labels:
    app: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
      - name: person-api
        image: marlonruiz/person-api:3
        ports:
        - containerPort: 8080
        
